// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/portfolio": {
    params: {};
  };
  "/admin": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/portfolio" | "/admin";
  };
  "routes/portfolio/route.tsx": {
    id: "routes/portfolio";
    page: "/portfolio";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/admin/route.tsx": {
    id: "routes/admin";
    page: "/admin";
  };
};